DEBUG: true 

sampling_rate: 3000 # ms

Node:
  id: "A01"
  location_name: "Prototype Monitor"
  lat: 30.631701
  lon: 76.725323

Sensors:
  DFRobotCOSensor:
    id: 20
    type: "DFRobotCOSensor"
    part_name: "DFRobot CO Sensor"
    comms: "HARDWARE_SERIAL"
    port_no: 1
    baud_rate: 9600
    measurements:
        - measurement_id: 1
          name: "CO"
          unit: "ppm"
