DEBUG: true 

sampling_rate: 3000 # ms

Node:
  id: "A01"
  location_name: "Prototype Monitor"
  lat: 30.631701
  lon: 76.725323

Sensors:
  SO2Sensor:
    id: 20
    type: "SO2Sensor"
    part_name: "Winsen ZE-03"
    comms: "HARDWARE_SERIAL"
    port_no: 1 # 0 or 1 or 2 or 3 depending on which i2c it is
    baud_rate: 9600
    measurements:
        - measurement_id: 1
          name: "SO2"
          unit: "ppm"
