DEBUG: true 

sampling_rate: 3000 # ms

Node:
  id: "A01"
  location_name: "Prototype Monitor"
  lat: 30.631701
  lon: 76.725323

Sensors:
  OxygenSensor:
    id: 20
    type: "DFRobotOxygenSensor"
    part_name: "DFRobot Oxygen Winsen ME-O2"
    comms: "I2C"
    port_no: 2 # 0 or 1 or 2 or 3 depending on which i2c it is
    i2c_address: 0x73
    measurements:
        - measurement_id: 1
          name: "pm1"
          unit: "ppm"
